/*
 Copyright (c) 2021, Robby, Kansas State University
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 1. Redistributions of source code must retain the above copyright notice, this
    list of conditions and the following disclaimer.
 2. Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package org.sireum.intellij.logika;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import org.sireum.intellij.PlaceholderTextField;

import javax.swing.*;
import java.awt.*;

public class LogikaToolWindowForm {
    public JPanel logikaToolWindowPanel;
    private JScrollPane logikaToolListScrollPane;
    public JList<Object> logikaList;
    public JSplitPane logikaToolSplitPane;
    private JPanel logikaToolTextPane;
    private JScrollPane logikaToolTextScrollPane;
    private JPanel logikaToolTextInnerPane;
    public PlaceholderTextField logikaToolTextField;
    public JButton logikaToolTextExportButton;
    public JTextArea logikaTextArea;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        logikaToolWindowPanel = new JPanel();
        logikaToolWindowPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        logikaToolSplitPane = new JSplitPane();
        logikaToolSplitPane.setDividerLocation(128);
        logikaToolSplitPane.setDividerSize(3);
        logikaToolSplitPane.setForeground(new Color(-10197916));
        logikaToolSplitPane.setOneTouchExpandable(false);
        logikaToolSplitPane.setOrientation(0);
        logikaToolWindowPanel.add(logikaToolSplitPane, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        logikaToolListScrollPane = new JScrollPane();
        logikaToolSplitPane.setLeftComponent(logikaToolListScrollPane);
        logikaList = new JList();
        logikaList.setSelectionMode(0);
        logikaToolListScrollPane.setViewportView(logikaList);
        logikaToolTextPane = new JPanel();
        logikaToolTextPane.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        logikaToolSplitPane.setRightComponent(logikaToolTextPane);
        logikaToolTextScrollPane = new JScrollPane();
        logikaToolTextPane.add(logikaToolTextScrollPane, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        logikaTextArea = new JTextArea();
        logikaToolTextScrollPane.setViewportView(logikaTextArea);
        logikaToolTextInnerPane = new JPanel();
        logikaToolTextInnerPane.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        logikaToolTextPane.add(logikaToolTextInnerPane, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        logikaToolTextField = new PlaceholderTextField();
        logikaToolTextField.setEnabled(true);
        logikaToolTextField.setPlaceholder("");
        logikaToolTextField.setText("");
        logikaToolTextInnerPane.add(logikaToolTextField, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        logikaToolTextExportButton = new JButton();
        logikaToolTextExportButton.setIcon(new ImageIcon(getClass().getResource("/icon/export.png")));
        logikaToolTextExportButton.setText("");
        logikaToolTextExportButton.setToolTipText("Export ...");
        logikaToolTextInnerPane.add(logikaToolTextExportButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(30, 30), new Dimension(30, 30), new Dimension(30, 30), 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return logikaToolWindowPanel;
    }
}
