package org.sireum.intellij;

import javax.swing.*;
import java.awt.*;

public class ProblemToolWindowForm {
    protected JPanel problemPanel;
    protected JScrollPane problemScrollPane;
    protected JList<SireumToolWindowFactory.Problem> problemList;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        problemPanel = new JPanel();
        problemPanel.setLayout(new BorderLayout(0, 0));
        problemScrollPane = new JScrollPane();
        problemPanel.add(problemScrollPane, BorderLayout.CENTER);
        problemList = new JList();
        problemList.setSelectionMode(0);
        problemScrollPane.setViewportView(problemList);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return problemPanel;
    }
}
